name: peviitor.ro
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 210
    steps:
      - uses: actions/checkout@v3
      - name: run jmeter on github action
        uses: sebiboga/run-jmeter-github-action@main
