name: play with actions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
      version:
        description: 'Version'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
